name: gsheet_to_arb
version: 0.0.1
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/rahmat412/gsheet_to_arb

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  dart_style: ^2.0.0
  intl: ^0.20.2
  path: ^1.9.0
  googleapis_auth: ^1.5.0
  googleapis: ^13.1.0
  code_builder: ^4.10.0
  intl_translation: ^0.20.1
  json_annotation: ^4.8.1
  file_utils: ^1.0.1
  logging: ^1.2.0
  recase: ^4.1.0
  quiver: ^3.2.1
  yaml: ^3.1.2
  petitparser: ^6.0.2

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
